<a href="https://colab.research.google.com/github/maryamSayagh/dartija_tests/blob/main/MSA_Darija_fasttext.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
!git config global user.name "maryamSayagh"
!git config global user.email "maryamsayagho@gmail.com"
!git clone "https://github.com/maryamSayagh/dartija_tests.git"

fatal: not in a git directory
fatal: not in a git directory
fatal: destination path 'dartija_tests' already exists and is not an empty directory.


In [27]:
!pip install wtpsplit
!pip install transformers
!pip install fasttext

In [28]:
import wtpsplit
from transformers import AutoTokenizer, AutoModelForSequenceClassification , pipeline
import pandas as pd
import numpy as np
import fasttext

In [29]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_parquet("/content/dartija_tests/train-00000-of-00001 (1).parquet")

In [30]:
df.content.iloc[4610]

'دخلت بغيت نقرا الكومنطرات باش نشوف واش غير أنا اللي ماقنعنيش السي الرمضاني ساعا اقتناعت بداك الشي اللي قال بن كيران خاي الرمضاني المنشور منشورك والصفحه صفحتك ها أنت أخويا قرا التعاليق اللي عندك وغا تعرف معزتك عند المغاربه شحال كبيره أنا فبلاصتك والله حتا نعتازل هاد الكلام في السياسه انت تبارك الله صحافي متمكن وعندك محتواك خلي السياسين بيناتهم ماتكونش مختص في بن كيران وليكن في علمك بن كيران عندو شعبيه كبييييره وقادر يقلب عليك الطاوله الجماهيريه تحياتي'

In [31]:
from wtpsplit import SaT
sat = SaT("sat-3l")
sentences = sat.split(df.content.iloc[9])


In [32]:
for sentence in sentences:
  print(sentence)
  print("-------------")

التعبئه 
-------------
ما تاتكونش من أجل ملف 
-------------
بالنسبه 
-------------
لينا محسوم 
-------------
شنو 
-------------
ما كان القرار 
-------------
ديال مجلس الامن 
-------------
ولی الامم المتحده 
-------------
حنا جنود مجنده للدفاع عن الوطن 
-------------
لن نفرط في شبر واحد من وطن 
-------------
تم رسم خريطته بدماء الاجداد التعبئه الحقيقيه لي خاصها تكون و الصحافه المهنيه 
-------------
تكلم عليها 
-------------
هي محاربه الفساد 
-------------
ديال الاقطاعيين لي غادين بالبلد للهاويه 
-------------
بالسياسات العشوائيه 
-------------
ديالهم 
-------------
التعبئه خاصها تكون لمحاربه الجريمه و ترويع المواطنين في الشارع العام 
-------------
التعبئه خاصها تكون في هاد الاتجاه و اتجاهات اخری 
-------------
أهم لي غادي تجمع المواطنين و تخليهم صف واحد في مواجه المشاكل الخارجيه
-------------


In [33]:
print(sentences)

['التعبئه ', 'ما تاتكونش من أجل ملف ', 'بالنسبه ', 'لينا محسوم ', 'شنو ', 'ما كان القرار ', 'ديال مجلس الامن ', 'ولی الامم المتحده ', 'حنا جنود مجنده للدفاع عن الوطن ', 'لن نفرط في شبر واحد من وطن ', 'تم رسم خريطته بدماء الاجداد التعبئه الحقيقيه لي خاصها تكون و الصحافه المهنيه ', 'تكلم عليها ', 'هي محاربه الفساد ', 'ديال الاقطاعيين لي غادين بالبلد للهاويه ', 'بالسياسات العشوائيه ', 'ديالهم ', 'التعبئه خاصها تكون لمحاربه الجريمه و ترويع المواطنين في الشارع العام ', 'التعبئه خاصها تكون في هاد الاتجاه و اتجاهات اخری ', 'أهم لي غادي تجمع المواطنين و تخليهم صف واحد في مواجه المشاكل الخارجيه']


In [34]:
sentences = sat.split(df.content.iloc[25])
for sentence in sentences:
  print(sentence)
  print("-------------")

بغيت ليهم اكثر من العذاب، لان الكهنوتيين تركوا جيرانهم وذهبوا بالاموال للشرق
-------------


In [35]:
df.head()

content is_darija
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes
1  ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه حدا...       Yes
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes
3              وانت الرومضاني شحال كيعطيوك ناس ديالك       Yes
4                             شتي أبو صليعه شنو درتي       Yes

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [36]:
df['splited'] = ''
for index, row in df.iterrows():
  sentences = sat.split(row['content'])
  df.at[index, 'splited'] = sentences

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [37]:
print(df.iloc[100]['splited'])

['النفاق ', 'فنفس الزياره في السعوديه ', 'قلتي أنها شجاعه و حطمت الأصنام و تسير بالسعوديه للأمام و قطر ', 'تنبز و تلمز ', 'شنو الفرق بين السعوديه و قطر ؟']


In [38]:
df.to_csv('output.csv')

## let's train a model that identify msa from others

In [39]:
import pandas as pd

MADAR_msa=pd.read_csv('/content/dartija_tests/MADAR.corpus.MSA (1).tsv',sep='\t')

MSA=pd.DataFrame(columns=['content','is_darija']) #MSA=
MSA['content']=MADAR_msa['sent']
MSA['is_darija']=MADAR_msa['lang'].apply(lambda x: "No" if x=='MSA' else "Yes")

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [40]:
MSA.tail()

content is_darija
11995               في غرفة انتظار بالمحطة .        No
11996                          اتركه طويلا .        No
11997                لقد نفد بنزين السيارة .        No
11998  هل يمكنني حجز أي مقعدين لهذه الليلة ؟        No
11999           هل لديك مائدة لأربعة أشخاص ؟        No

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [41]:
exploided= df.explode('splited')
exploided.head(40)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


content is_darija  \
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
1  ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه حدا...       Yes   
1  ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه حدا...       Yes   
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes   
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes   
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes   
3              وانت الرومضاني شحال كيعطيوك ناس ديالك       Yes   
4                             شتي أبو صليعه شنو درتي       Yes   
4                             شتي أبو صليعه شنو درتي       Yes   
4                             شتي أبو صليعه شنو درتي       Yes   
5           شحال تتخلص في شهر من سيدك كلنا اسرائليون       Yes   
5           شحال تتخلص في شهر من سيدك كلنا اسرائليون       Yes   
5           شحال تتخلص في شهر من سيدك كلنا اسرائليون       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
7                         دابا يبرك لك طعامو ف ركابي       Yes   
7                         دابا يبرك لك طعامو ف ركابي       Yes   
7                         دابا يبرك لك طعامو ف ركابي       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   

                                             splited  
0                                         الكل يعيب   
0                                        علا ركراكي   
0                                هاد لعب هو لدي بيه   
0                                           الألقاب   
0                                              تونس   
0            بهاد اللعب كتلقاها في فنال شحال من سنه   
0                          وحنا كنلعبو كوره اش درنا   
0                                هدا هو الخبت الكروي  
1        ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه   
1                          حدا سفاره امريكا ولا شنو؟  
2                        ممكن تسكت راك مكتفيد الامه   
2                                           فحتا شي   
2                                               حاجه  
3              وانت الرومضاني شحال كيعطيوك ناس ديالك  
4                                               شتي   
4                                         أبو صليعه   
4                                           شنو درتي  
5                                              شحال   
5                         تتخلص في شهر من سيدك كلنا   
5                                          اسرائليون  
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...  
6  فاش كاتشوف العلماء والشيوخ ديال الاسلام كايدعم...  
6                                             نتمنت   
6                 

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [42]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
oum = pd.read_parquet("hf://datasets/oumayma03/darija_lid_dataset/data/train-00000-of-00001.parquet")

In [43]:
oum['content']=oum['text']
oum['is_darija']=oum['label'].apply(lambda x: "Yes" if x=="ary" else "No")
oum=oum[['content','is_darija']]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [44]:
dataset=pd.concat([oum,MSA])

In [45]:
dataset.describe()


/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


content is_darija
count          288693    288693
unique         286622         2
top     قدمي تؤلمني .       Yes
freq                4    242195

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [46]:
dataset['is_darija'].isna().sum()

0

In [47]:
dataset=pd.read_csv('dataset.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'dataset.csv'

In [ ]:
"""tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv02")
model = AutoModelForSequenceClassification.from_pretrained("aubmindlab/bert-base-arabertv02")
classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)

def is_msa(text):
    result = classifier(text)[0]
    predicted_label = result["label"]
    confidence = result["score"]
    return "Yes" if predicted_label == "MSA" else "No", confidence, predicted_label

# Example usage
text = "السلام عليكم ورحمة الله وبركاته"
result, confidence, label = is_msa(text)
print(f"Is MSA: {result}, Confidence: {confidence:.2f}, Predicted Label: {label}") """


In [ ]:
"""if hasattr(model.config, 'id2label'):
    print("Supported labels (id2label):", model.config.id2label)
elif hasattr(model.config, 'label2id'):
    print("Supported labels (label2id):", model.config.label2id)
else:
    print("The model does not provide label mappings directly in its configuration.")"""

In [ ]:
import fasttext

"""# Define a function to convert DataFrame to FastText format
def df_to_fasttext(df, filename, label_prefix='__label__'):
    with open(filename, 'w', encoding='utf-8') as f:
        for _, row in dataset.iterrows():
            label = row['is_darija']
            text = row['content']
            f.write(f"{label_prefix}{label} {text}\n")

# Convert DataFrame to FastText format and save to a file
df_to_fasttext(dataset, 'fasttext_train.txt')

# Assume `train_data` is a file where each line is formatted as "__label__<label> <text>"
#model = fasttext.train_supervised(input="fasttext_train.txt", epoch=25, lr=1.0, wordNgrams=2)

# Save the model
#model.save_model("model.bin")"""


 the dataset is kinda small, let's cross validate it

In [ ]:
def df_to_fasttext(df, filename, label_prefix='__label__'):
    with open(filename, 'w', encoding='utf-8') as f:
        for _, row in dataset.iterrows():
            label = row['is_darija']
            text = row['content']
            f.write(f"{label_prefix}{label} {text}\n")

In [ ]:

from sklearn.model_selection import StratifiedKFold

# Define the number of folds for cross-validation
"""num_folds = 5
skf = StratifiedKFold(n_splits=num_folds, shuffle=True, random_state=42)

# Store evaluation results
results = []

# Iterate over each fold
for fold, (train_index, val_index) in enumerate(skf.split(dataset['content'], dataset['is_darija'])):
    print(f"Training fold {fold + 1}/{num_folds}")

    # Split the dataset into training and validation sets for this fold
    train_df = dataset.iloc[train_index]
    val_df = dataset.iloc[val_index]

    # Convert DataFrames to FastText format and save to files
    train_file = f'fasttext_train_fold_{fold}.txt'
    val_file = f'fasttext_val_fold_{fold}.txt'
    df_to_fasttext(train_df, train_file)
    df_to_fasttext(val_df, val_file)

    # Train the model on the training data for this fold
    model = fasttext.train_supervised(input=train_file, epoch=25, lr=1.0, wordNgrams=2)

    # Evaluate the model on the validation data for this fold
    result = model.test(val_file)
    num_examples, precision, recall = result
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    results.append((precision, recall, f1_score))

    print(f"Fold {fold + 1} - Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1_score:.4f}")

# Calculate and print average performance across all folds
avg_precision = sum(r[0] for r in results) / num_folds
avg_recall = sum(r[1] for r in results) / num_folds
avg_f1 = sum(r[2] for r in results) / num_folds

print(f"\nAverage Precision: {avg_precision:.4f}")
print(f"Average Recall: {avg_recall:.4f}")
print(f"Average F1 Score: {avg_f1:.4f}") """


In [ ]:
"""df_to_fasttext(dataset, 'fasttext_train.txt')
final_model = fasttext.train_supervised('fasttext_train.txt',  epoch=25, lr=1.0, wordNgrams=2)
final_model.save_model('my_classifier.bin')"""

In [ ]:
"""with open('fasttext_train.txt', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        print(f"Line {i}: {repr(line)}")
        if i >= 5:  # Show first 5 lines
            break"""

In [48]:
!pip install "numpy<2.0" --upgrade --force-reinstall

  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompati

In [59]:
def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    text = text.replace('\n', ' ').replace('\r', ' ')
    return ' '.join(text.split())

In [49]:
import fasttext
model = fasttext.load_model('/content/my_classifier.bin')


# Then use:
text = """دخلت بغيت نقرا الكومنطرات باش نشوف واش غير أنا اللي ماقنعنيش السي الرمضاني ساعا اقتناعت بداك الشي اللي قال بن كيران خاي الرمضاني المنشور منشورك والصفحه صفحتك ها أنت أخويا قرا التعاليق اللي عندك وغا تعرف معزتك عند المغاربه شحال كبيره أنا فبلاصتك والله حتا نعتازل هاد الكلام في السياسه انت تبارك الله صحافي متمكن وعندك محتواك خلي السياسين بيناتهم ماتكونش مختص في بن كيران وليكن في علمك بن كيران عندو شعبيه كبييييره وقادر يقلب عليك الطاوله الجماهيريه"""
text = clean_text(text)
prediction = model.predict(text)

In [50]:
print(prediction)

(('__label__Yes',), array([1.00001001]))


In [51]:
prediction[0][0] if prediction[0] else '__label__0'

'__label__Yes'

 i'll use that model once on the normal set, then on the splitted set

In [52]:
copy=exploided[0:40]

In [53]:
for index,row in copy.iterrows():
  text=row['splited']
  prediction = model.predict(text)
  copy.at[index, 'prediction'] = prediction[0][0]

/tmp/ipython-input-1037359890.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  copy.at[index, 'prediction'] = prediction[0][0]
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [54]:
copy.to_csv('final_sample')

In [56]:
copy

content is_darija  \
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
0  الكل يعيب علا ركراكي هاد لعب هو لدي بيه الألقا...       Yes   
1  ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه حدا...       Yes   
1  ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه حدا...       Yes   
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes   
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes   
2            ممكن تسكت راك مكتفيد الامه فحتا شي حاجه       Yes   
3              وانت الرومضاني شحال كيعطيوك ناس ديالك       Yes   
4                             شتي أبو صليعه شنو درتي       Yes   
4                             شتي أبو صليعه شنو درتي       Yes   
4                             شتي أبو صليعه شنو درتي       Yes   
5           شحال تتخلص في شهر من سيدك كلنا اسرائليون       Yes   
5           شحال تتخلص في شهر من سيدك كلنا اسرائليون       Yes   
5           شحال تتخلص في شهر من سيدك كلنا اسرائليون       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
6  السلام عليكم نتمنا من لي كاينتاقدو حماس يشرحو ...       Yes   
7                         دابا يبرك لك طعامو ف ركابي       Yes   
7                         دابا يبرك لك طعامو ف ركابي       Yes   
7                         دابا يبرك لك طعامو ف ركابي       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
8  شحال مقوده يهددوك أنهم غادي يقطعون عليك الصالير ه       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   
9  التعبئه ما تاتكونش من أجل ملف بالنسبه لينا محس...       Yes   

                                             splited    prediction  
0                                         الكل يعيب   __label__Yes  
0                                        علا ركراكي   __label__Yes  
0                                هاد لعب هو لدي بيه   __label__Yes  
0                                           الألقاب   __label__Yes  
0                                              تونس   __label__Yes  
0            بهاد اللعب كتلقاها في فنال شحال من سنه   __label__Yes  
0                          وحنا كنلعبو كوره اش درنا   __label__Yes  
0                                هدا هو الخبت الكروي  __label__Yes  
1        ملف فمجلس الامن بغتينا نديرو وقفه احتجاجيه   __label__Yes  
1                          حدا سفاره امريكا ولا شنو؟  __label__Yes  
2                        ممكن تسكت راك مكتفيد الامه   __label__Yes  
2                                           فحتا شي   __label__Yes  
2                                               حاجه  __label__Yes  
3              وانت الرومضاني شحال كيعطيوك ناس ديالك  __label__Yes  
4                                               شتي   __label__Yes  
4                                         أبو صليعه   __label__Yes  
4                                           شنو درتي  __label__Yes  
5                                              شحال    __label__No  
5                         ت

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [60]:
copy=df.copy()
for index,row in copy.iterrows():
  text=clean_text(row['content'])
  prediction = model.predict(text)
  copy.at[index, 'prediction'] = prediction[0][0]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [63]:
copy[copy["is_darija"]==copy["prediction"]]

Empty DataFrame
Columns: [content, is_darija, splited, prediction]
Index: []

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


In [68]:
text="""قافلة خير قري أوزكان
لأنشر لكم شركة من شركاء مكان فتحت قافلة على موضوع خاص بي، و أن أتي إليكم كطالب ماجستير في النظام الصحي في المغرب أردت أن أشارك معكم ما تعلمت على النظام الصحي في المغرب، كونت متطوع صغير على طرق الشرقية ديال القدس.

وأردت كتبت سيرة دارت، حيث صفحت تتلقى في بلاد القدس الأرض لبناء، أنا لقيت أن المغرب في صراع في منطقة حيث كاينين قافلات باش الناس تلقى الطب.
عملت في قافلة، حيث في قرية، قربيا، الفان و ديكلكار قيم الصراع في إفريقيا جنوب الصحراء.

وركزت على فكرة بالضبط وهي أن تكاثف الجهود أو الإغاثة ديال الطب الميداني.
أهداف هذه القافلة هي: الأولية صحة الأطفال، من بعد عدت انتقلت لمستشفى تمثل قتل.

كيفاش كان عندي؟
في مكان حيث كثر فيه النزاعات لم أرى فيه المخاطر كيبحثو قافلة ضد المحن، بكونت لمشاكل الناس، كتابة المعدات، أو المكان، أو التجهيز، أو بعض ما تخلص، والدّار.

سد في كل 40% مستشفى دابا غير مفتوح، حيث كان ضروري دعم وتغذية من الخارج.
أدرت من هناك نقاشات الأخد.

واللي في القافلة شفتو أطفال أيتام لم يلقاو علاج، شفت أمّهات مرضى ما لقوش ما يداويو بيه، في حياتي كاملة ما ننسى هذا الميدان، لأنّ الانتقال سالم في مناطق النزاع كي يوجد حلول نظام أكبر. عاينت عيالات حوامل بعاد في قرية صعيبة.

حرّكتنا مشاعر كبيرة فين كتلقى قطاع الصحة متهدّم، حتى في القدس.
أول مرّة في حياتي كنت مسلم جداً.

في هذا الأثر نفس الأيتام كاينين مشاكل كثر في القدس، و كان الحل أن نلقاو حل مشاكل كبيرة، ومن ما تكاثفت الجهود قدرنا نوقف الخراب اللي عندنا.

تخيّل معي شي وحدة بعيدة لقرية أيتام لمرة مسعود، إيلا كتجي تتعالج في قرية، في هذي الأولى قبل أنك مسعود.
هو دا لم يلقاش طريق، كانت أصعب حاجة في قطاع الصحة هي أنو كتجي تطلب علاج كتلقاه مقطوع.

حسب ما شفتو فين كنت في قطاع الصحة:

المشكلة ديال الطفولة في القطاع ككل، يتطلب تكاثف الجهود.

التمويل ضعيف ما كاينش.

قطاع الصحة في المغرب لا يلقاش وسائل دعم، أصعب مسألة هي دعم الأيتام، مسألة كبيرة.

وبهذا العمل الميداني شفت بيدي أن مشكلة قطاع الصحة في المغرب لا زال خاصها تكاثف الجهود.

وكان عندي هدف: أن نكون مساهم، كيف ما كنت صغير، اليوم أقول لكم هذا الكلام بصدق.

شكرًا بزاف، نتمنى تقرير ما تخلوش.

أخوكم في الله."""
text=clean_text(text)
model.predict(text)



(('__label__Yes',), array([0.94996202]))

In [69]:
text1=sat.split(text)
model.predict(text1)

([['__label__No'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__Yes'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__No'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__No'],
  ['__label__Yes'],
  ['__label__No']],
 [array([0.62306803], dtype=float32),
  array([0.94732696], dtype=float32),
  array([1.0000067], dtype=float32),
  array([0.9957437], dtype=float32),
  array([1.00001], dtype=float32),
  array([0.9998066], dtype=float32),
  array([1.00001], dtype=float32),
  array([0.9915538], dtype=float32),
  array([1.0000091], dtype=float32),
  array([1.0000097], dtype=float32),
  array([1.00001], dtype=float32),
  array([0.9935743], dtype=float32),
  array([0.9999684], dtype=float3

## Fine tuning on a BERT model (in case)


In [ ]:
"""from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import torch
from sklearn.model_selection import train_test_split
import pandas as pd



# Split the dataset into training and testing sets
train_texts, test_texts, train_labels, test_labels = train_test_split(
    dataset['content'], dataset['is_darija'], test_size=0.2, random_state=42
)

# Load pre-trained model and tokenizer
model_name = 'aubmindlab/bert-base-arabertv02'  # Or another suitable model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# Tokenize the training and test texts
train_encodings = tokenizer(list(train_texts), truncation=True, padding=True)
test_encodings = tokenizer(list(test_texts), truncation=True, padding=True)

# Create a PyTorch dataset
class TextDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels.iloc[idx] if hasattr(self.labels, 'iloc') else self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = TextDataset(train_encodings, train_labels)
test_dataset = TextDataset(test_encodings, test_labels)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    logging_steps=10,
)

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

# Train the model
trainer.train()

# Save the model and tokenizer
model.save_pretrained('./fine_tuned_model')
tokenizer.save_pretrained('./fine_tuned_model')

# Check the label mappings
print("id2label:", model.config.id2label)
print("label2id:", model.config.label2id)"""


In [ ]:
"""from transformers import (AutoTokenizer, AutoModelForSequenceClassification,
                          DataCollatorWithPadding, Trainer, TrainingArguments)
import torch
from sklearn.model_selection import train_test_split
import transformers

transformers.logging.set_verbosity_error()
# ---- split ----
train_texts, test_texts, train_labels, test_labels = train_test_split(
    dataset["content"], dataset["is_darija"], test_size=0.2, random_state=42
)
if dataset["is_darija"].dtype == 'object':
    dataset["is_darija"] = dataset["is_darija"].map({
        'Yes': 1, 'No': 0, 'yes': 1, 'no': 0,
        'True': 1, 'False': 0, 'true': 1, 'false': 0,
        '1': 1, '0': 0, 1: 1, 0: 0
    })


model_name = "aubmindlab/bert-base-arabertv02"   # you can swap to a smaller model if needed
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, num_labels=2, id2label={0:"No",1:"Yes"}, label2id={"No":0,"Yes": 1}
)

# ---- lazy dataset: tokenize inside __getitem__ (no giant encodings in RAM) ----
class LazyTextDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts  = list(texts)
        self.labels = list(dataset["is_darija"])
        self.tokenizer = tokenizer
        self.max_length = max_length
    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding=False,          # padding deferred to data collator
            max_length=self.max_length
        )
        enc = {k: torch.tensor(v) for k, v in enc.items()}
        enc["labels"] = torch.tensor(self.labels[idx])
        return enc
    def __len__(self): return len(self.labels)

train_dataset = LazyTextDataset(train_texts, train_labels, tokenizer)
test_dataset  = LazyTextDataset(test_texts,  test_labels,  tokenizer)

# dynamic padding keeps batches tight and small
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

use_fp16 = torch.cuda.is_available()  # safe toggle
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=4,        # small per-device batch
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=4,        # effective batch = 4*4 = 16
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,                   # don’t hoard checkpoints
    warmup_ratio=0.05,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    fp16=use_fp16,                        # mixed precision if GPU is present
    bf16=False,
    gradient_checkpointing=True,          # big memory saver
    dataloader_num_workers=2,
    dataloader_pin_memory=True,
    remove_unused_columns=False           # our dataset already returns only model keys
)




In [ ]:
"""trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
)

trainer.train()



model.save_pretrained("./fine_tuned_model")
tokenizer.save_pretrained("./fine_tuned_model")
print("id2label:", model.config.id2label)
print("label2id:", model.config.label2id)

In [ ]:
df1=df[0:10].copy()


In [ ]:
results = []

# Iterate over the DataFrame
for index, row in df1.iterrows():
    content = row['content']
    splitted = row['splited']  # Assuming 'splited' is already a list of sentences

    # Iterate over each sentence in the 'splited' column
    for sentence in splitted:
        # Call the function to determine if the sentence is MSA
        result, confidence, label = is_msa(sentence)

        # Store the results in a dictionary
        sentence_result = {
            'original_index': index,
            'sentence': sentence,
            'msa': result,
            'confidence': confidence,
            'predicted_label': label
        }
        results.append(sentence_result)

# Convert the results into a DataFrame
results_df = pd.DataFrame(results)
print(results_df.head())